import type { Flashcard, Question } from '../../utils/validation/kitSchema';

/**
 * Flashcards are derived deterministically from each question's answer
 * outline rather than generated by a separate LLM call: the content already
 * exists (question prompt = front, answer outline = back), and spending
 * another model call to restate it would just burn free-tier budget for no
 * real gain. See README "Design choices".
 */
export function buildFlashcards(questions: Question[], nextId: () => string): Flashcard[] {
  return questions.map((q, i) => ({
    id: nextId(),
    front: q.prompt,
    back: q.answer_outline || 'No answer outline was generated for this question yet.',
    requirement_ids: q.requirement_ids,
    state: 'generated' as const,
    order: i,
    practice: {
      times_reviewed: 0,
      last_confidence: null,
      confidence_history: [],
      next_due_at: null,
    },
    source_question_id: q.id,
  }));
}
